### ISSUE TITLE
push/pull ging niet goed CSS

### ISSUE THREAD

**Issue by Anna-Kyra** [KaanKalmi/look-and-feel-living-styleguide#1]
Had de overall CSS verandert + de buttons er ingezet en vormgegeven, maar ik zie de verandering die ik heb gedaan niet meer terug in de CSS van de live url. Het staat wel lokaal goed overigens. Help

**Comment by KaanKalmi** [comment]
Github pages is soms traag met het online zetten van de nieuwe pushed commits, ligt niet aan jou. Zou als het goed is er nu in moeten zitten tho?

**Comment by Anna-Kyra** [comment]
Thx! Zit erin nu, maar wel met teveel info in de HTML ja, komt geloof ik door mij met het verkeerd te pushen/pullen.
