### ISSUE TITLE
List-styles half zichtbaar

### ISSUE THREAD

**Issue by Robin1224** [KaanKalmi/look-and-feel-living-styleguide#12]
In de DO'S en DON'TS sections zijn er lists waar de `list-style` niet aangepast is. 

Dit is in principe oke, maar door de positionering zijn de bullet point symbolen maar half te zien.

![image](https://github.com/KaanKalmi/look-and-feel-living-styleguide/assets/81151231/9e056f50-228b-4af0-a90f-40d0267254e6)

Ik zou óf de `list-style` property aanpassen naar `none` in de css, óf de tekst meer naar rechts zetten zodat de symbolen zichtbaar zijn.

**Comment by KaanKalmi** [comment]
fixed
