### ISSUE TITLE
Witruimte typografie

### ISSUE THREAD

**Issue by Robin1224** [KaanKalmi/look-and-feel-living-styleguide#13]
<img src="https://github.com/KaanKalmi/look-and-feel-living-styleguide/assets/81151231/79cc64fa-e361-46ac-89eb-82d37dd4f86d" width="300" align="left">

In de typografie sectie is er weinig witruimte. Het zou overzichtelijker zijn als er iets meer witruimte is tussen de tekst in de typografie sectie.

**Comment by KaanKalmi** [comment]
dit is als het goed is gefixt nu
