### ISSUE TITLE
Example code in HTML

### ISSUE THREAD

**Issue by Robin1224** [KaanKalmi/look-and-feel-living-styleguide#14]
![image](https://github.com/KaanKalmi/look-and-feel-living-styleguide/assets/81151231/aac58f0c-f3b9-4449-84f8-5d46a114290d)

Binnen de typografie sectie is er example code, maar dit is volgens mij niet de code die relevant is voor de typografie. 

In de code is namelijk alleen HTML aanwezig, terwijl je wanneer je naar de living style guide kijkt eigenlijk CSS code wilt hebben om de styling makkelijk te kunnen toepassen.

**Suggestie:** de styling code voor de typografie neerzetten als de example code, in plaats van plain HTML elementen.

**Comment by Robin1224** [comment]
Ik zie nu dat dit niet alleen bij typografie het geval is.

Ik denk dat het relevanter is om code in de styleguide te zetten voor styling, ipv alleen HTML. 

Er staat op veel plekken namelijk code waar in principe alleen staat 'gebruik de class "button" voor buttons', maar het is juist de styling van die class dat relevant is.

**Comment by KaanKalmi** [comment]
nu in behandeling, bijna af nog 1 onderdeel moet gedaan worden

**Comment by KaanKalmi** [comment]
De example code moest wel in HTML
