### ISSUE TITLE
Fonts text input & text-area

### ISSUE THREAD

**Issue by Robin1224** [KaanKalmi/look-and-feel-living-styleguide#15]
![image](https://github.com/KaanKalmi/look-and-feel-living-styleguide/assets/81151231/48f0395b-9cdc-44d4-9695-9a764a5acf77)

Text-area en text input hebben beiden verschillende fonts. Het zou consistenter zijn om in text-area en text inputs dezelfde fonts te gebruiken.

**Suggestie:** de text input heeft font Arial. Ik zou hetzelfde font toepassen op de text-area.

**Comment by Anna-Kyra** [comment]
Gefixt!
