### ISSUE TITLE
Navigatie

### ISSUE THREAD

**Issue by Robin1224** [KaanKalmi/look-and-feel-living-styleguide#16]
Alles op 1 pagina hebben is niks mis mee, maar toch zou het handig zijn om snel een specifieke sectie te kunnen vinden.

Met een navigatie zou de pagina overzichtelijker en makkelijker te gebruiken zijn. 

Je kan dit toevoegen zonder de pagina structuur te veranderen door `id` tags toe te voegen op bijvoorbeeld je h2 elementen. Als je dan in de navigatie links zet naar deze `id`s, dan scrollt de pagina naar de juiste plek wanneer je er op klikt, maar kun je alsnog alles netjes op 1 pagina houden.

**Suggestie:** voeg een navigatie toe met links naar `id`s verder op de pagina. Zo behoud je de pagina structuur, maar zorg je alsnog voor meer overzicht.

[meer info](https://www.w3docs.com/snippets/html/how-to-create-an-anchor-link-to-jump-to-a-specific-part-of-a-page.html)

**Comment by KaanKalmi** [comment]
[fixed ](https://github.com/KaanKalmi/look-and-feel-living-styleguide/commit/8ce26d64f85015e0c19f8de36ea174d11f5cce36)
