### ISSUE TITLE
Kleur contrast titels 

### ISSUE THREAD

**Issue by Stefan-Espant** [KaanKalmi/look-and-feel-living-styleguide#5]
Hebben jullie over het kleurgebruik nagedacht van de titels? Kijk of jullie deze ook toegankelijk kunnen maken.

<img width="371" alt="Schermafbeelding 2023-11-15 om 11 11 00" src="https://github.com/KaanKalmi/look-and-feel-living-styleguide/assets/89298385/f4fb824a-f6dd-40ae-86dc-f838fc2afcc7">

**Comment by KaanKalmi** [comment]
![image](https://github.com/KaanKalmi/look-and-feel-living-styleguide/assets/144000125/7d7be84c-68b8-4aec-a4a3-0e16f04edfe5)

fixed
